services:
  - type: web
    name: finassistai-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: PORT
        generateValue: true
    autoDeploy: false
